### PR TITLE
[MRESOLVER-27] turn api, spi and utils into Java 9 modules

### PR DESCRIPTION
**Pull request by rfscholte**
provided a `module-info` for the 3 mentioned modules. This i,plies, that the automatic module cannot be defined globally, because it is not allowed to have both a module descriptor and an automatic-module-name entry.

@cstamas not sure why the build fails, seems some java parser doesn't understand module descriptors.

### CODE REVIEW

**Comment by cstamas** [comment]
Yup, we generate now this page (as in 1.x it is fully out of sync and maintaining it is a hell):
https://maven.apache.org/resolver-archives/resolver-2.0.0-alpha-11/configuration.html

Using this code here, that I smashed just to get away with it... 
https://github.com/apache/maven-resolver/blob/master/maven-resolver-tools/src/main/java/org/eclipse/aether/tools/CollectConfiguration.java

**Comment by cstamas** [comment]
Is executed here
https://github.com/apache/maven-resolver/blob/master/maven-resolver-tools/pom.xml#L85

Probably adding a simple file/path exclusion would do it. The code is really interested in Javadoc.

**Comment by rfscholte** [comment]
awesome, that fixed it.

**Comment by HannesWell** [comment]
You could maybe use the already configured `bnd-maven-plugin` to generate the `modules-info.java/class` based on the exported/imported package also configured in the OSGi MANIFEST.MF:

Maybe a simple `-jpms-module-info` is already sufficient, but configuring it is possible:
https://bnd.bndtools.org/releases/6.4.0/chapters/330-jpms.html

If you are interested I can work out a solution.

**Comment by rfscholte** [comment]
I'll leave the preferred approach up to @cstamas . 
I just think that starting with 2.0.0 is a great opportunity to provide these module descriptors when possible. I already noticed that it will be an issue for several third party issues, but if there's a clear separation of libraries and applications, only applications should care about the implementation and libraries could start adopting these api/spi/utils.

**Comment by rfscholte** [comment]
The latest merge broke this PR. And it seems like if we go for my proposal, I need to revert some stuf again. @HannesWell maybe you should give it a try.

**Comment by HannesWell** [comment]
> I just think that starting with 2.0.0 is a great opportunity to provide these module descriptors when possible. 

Agree.

> The latest merge broke this PR. And it seems like if we go for my proposal, I need to revert some stuf again. @HannesWell maybe you should give it a try.

Yes, I expected that. But since #509 was against `resolver-1.9.x` and this is against `master` I'm not sure how that broke this exact PR? Or do you mean if a similar change is applied to the master or this is back-ported to `1.9.x`?
Anyways I can of course try the suggested approach after #509 has been forward-ported.

**Comment by rfscholte** [comment]
Having a second look, we need to put back the maven-jar-plugin back anyway in case there's an automatic module name, that's something that cannot be defined globally

**Comment by HannesWell** [comment]
> Yes, I expected that. But since #509 was against `resolver-1.9.x` and this is against `master` I'm not sure how that broke this exact PR? Or do you mean if a similar change is applied to the master or this is back-ported to `1.9.x`?

Never-mind I didn't saw https://github.com/apache/maven-resolver/pull/512.

> Having a second look, we need to put back the maven-jar-plugin back anyway in case there's an automatic module name, that's something that cannot be defined globally

I have to look into this first. Do you mind if I create an alternative PR using the suggested automatic generation based on the bnd-maven-plugin? Then we can see how both work?

**Comment by cstamas** [comment]
@rfscholte Could you please pull out into separate PR the one liner "tool" change (that leaves our `/module-info.java`)? As that change is good on it's own, and the tool will not want to parse anything else than "plain" java source...

**Comment by rfscholte** [comment]
@cstamas sure, https://github.com/apache/maven-resolver/pull/514

**Comment by cstamas** [comment]
Thanks!

**Comment by HannesWell** [comment]
> > Having a second look, we need to put back the maven-jar-plugin back anyway in case there's an automatic module name, that's something that cannot be defined globally
> 
> I have to look into this first. Do you mind if I create an alternative PR using the suggested automatic generation based on the bnd-maven-plugin? Then we can see how both work?

Please have a look at https://github.com/apache/maven-resolver/pull/516.

**Comment by rfscholte** [comment]
Superceded by https://github.com/apache/maven-resolver/pull/516

**Comment by jira-importer** [comment]
Resolve #820

**Comment by jira-importer** [comment]
Resolve #820

**Pull request closed without merging**
