### PR TITLE
Clarify `file-lock` being a distributed name lock

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by cstamas** [comment]
Well, it is not "distributed" as is not for multi hosts case. I'd rather distinguish like ST, MT, MP and MH (single thread, multi thread, multi process/single-host and multi-host).

File is MP, redisson is MH in this manner.

**Comment by kwin** [comment]
Why is it not MH if you have e.g. a NFS network share mounted?

**Comment by cstamas** [comment]
Unsure about NFS file locking... @michael-o ?

**Comment by cstamas** [comment]
In short: if your FS correctly support locking, should work. Local FS usually is okay. For NFS your mileage may vary.

**Comment by michael-o** [comment]
This should also go to the docs.

**Comment by cstamas** [comment]
Superseded by https://github.com/apache/maven-resolver/pull/185

**Pull request closed without merging**
