### PR TITLE
[MRESOLVER-264] Make file locking the default

### PR DESCRIPTION
**Pull request by cstamas**
Make file lock factory and file-gav mapper the default.

---

https://issues.apache.org/jira/browse/MRESOLVER-264

### CODE REVIEW

**Review by gnodet — APPROVED** [review]

**Comment by michael-o** [comment]
What about docs?

**Comment by jira-importer** [comment]
Resolve #759

**Comment by jira-importer** [comment]
Resolve #759

**Comment by hvoynov** [comment]
https://maven.apache.org/components/resolver/maven-resolver-impl/synccontextfactory.html
Seems docs are not updates still.

**Pull request merged**
