### PR TITLE
[1.9.x] Update dependencies

### PR DESCRIPTION
**Pull request by cstamas**
Changes:
* hazelcast 5.3.7
* redisson 3.28.0
* commons-codec 1.16.1
* sisu 0.9.0.M2
* guice 6.0.0 (and guava 33.1.0)
* jetty 9.4.54 (used in tests)
* maven 3.9.6 (used in demos)

---

https://issues.apache.org/jira/browse/MRESOLVER-527
https://issues.apache.org/jira/browse/MRESOLVER-528
https://issues.apache.org/jira/browse/MRESOLVER-529
https://issues.apache.org/jira/browse/MRESOLVER-530
https://issues.apache.org/jira/browse/MRESOLVER-531
https://issues.apache.org/jira/browse/MRESOLVER-532
https://issues.apache.org/jira/browse/MRESOLVER-533

### CODE REVIEW

**Review by michael-o — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #1194

**Comment by jira-importer** [comment]
Resolve #1199

**Comment by jira-importer** [comment]
Resolve #1204

**Comment by jira-importer** [comment]
Resolve #1206

**Comment by jira-importer** [comment]
Resolve #1207

**Pull request merged**
