### PR TITLE
[MRESOLVER-103] replace some deprecated classes

### PR DESCRIPTION
**Pull request by elharo**
@michael-o

### CODE REVIEW

**Comment by elharo** [comment]
https://stackoverflow.com/questions/29207694/apache-httpclient-4-4-hostnameverifier-transition-from-4-3-x

**Comment by elharo** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project maven-resolver-transport-http: Compilation failure
[ERROR] /home/jenkins/jenkins-slave/workspace/maven-box_maven-resolver_depre/m/maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/GlobalState.java:[177,29] no suitable constructor found for Scheme(java.lang.String,int,org.eclipse.aether.transport.http.SslSocketFactory)
[ERROR]     constructor org.apache.http.conn.scheme.Scheme.Scheme(java.lang.String,org.apache.http.conn.scheme.SocketFactory,int) is not applicable
[ERROR]       (actual argument int cannot be converted to org.apache.http.conn.scheme.SocketFactory by method invocation conversion)
[ERROR]     constructor org.apache.http.conn.scheme.Scheme.Scheme(java.lang.String,int,org.apache.http.conn.scheme.SchemeSocketFactory) is not applicable
[ERROR]       (actual argument org.eclipse.aether.transport.http.SslSocketFactory cannot be converted to org.apache.http.conn.scheme.SchemeSocketFactory by method invocation conversion)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :maven-resolver-transport-http

**Comment by michael-o** [comment]
I have been recently reviewing Resolver. To be frank the HTTP transport is basically duplicate of Wagon HTTP Provider. If it is possible to properly use Resolver with Wagon and its providers outside of Maven space and especially with Resolver Ant Tasks, I'd be included to remove this module from the next major version.

**Comment by elharo** [comment]
I'm all in favor of removing duplicate code. There's a lot of random, reimplemented cruft throughout the plugins. Perhaps start by deprecating these packages and adding instructions for porting to wagon http?

**Comment by michael-o** [comment]
Before we do this we need to verify that everything will still work outside of Maven. E.g., custom, standalone code and out Maven Resolver Ant Tasks.

**Comment by jira-importer** [comment]
Resolve #867

**Comment by jira-importer** [comment]
Resolve #867

**Pull request closed without merging**
