### PR TITLE
[MRESOLVER-162] Restore binary compatibility

### PR DESCRIPTION
**Pull request by cstamas**
And make demos work again.

### CODE REVIEW

**Comment by michael-o** [comment]
I'd like to settle this. How did you notice that demos don't work?

**Comment by cstamas** [comment]
Try to run them... if you look at demo snippets, they are built but not run by maven build, those are "demo" code that all have `static void main`, so I just ran them from my IDE, and they all failed with CNFEx (as they pull maven-resolver-provider from maven) for ServiceLocator in "old" place, but failing to find it.

**Comment by michael-o** [comment]
Btw, when you try to compile Maven with Resolver master it does not work either.

**Comment by jira-importer** [comment]
Resolve #947

**Pull request closed without merging**
