### PR TITLE
[MRESOLVER-9] Managed dependencies are not honoured when resolving a …

### PR DESCRIPTION
**Pull request by gnodet**
…dependency graph

### CODE REVIEW

**Comment by gnodet** [comment]
This PR actually fixes https://issues.apache.org/jira/projects/MNG/issues/MNG-7003 but it may also broke other test cases.  I'll run the IT suite on maven 4 to check.

**Comment by michael-o** [comment]
Here is the original fix: https://github.com/ChristianSchulte/maven-resolver/commit/ed4322f297fa2cb003a0eb91120b2d4f84561d3c Please compare and judge.

**Comment by gnodet** [comment]
> Here is the original fix: [ChristianSchulte@ed4322f](https://github.com/ChristianSchulte/maven-resolver/commit/ed4322f297fa2cb003a0eb91120b2d4f84561d3c) Please compare and judge.

Yes, I saw it. Fwiw, I don't think the issue is exactly the same as my problem lies in the `DependencyManager` and not in the `DependencySelector`.  Both are problems related to dependency management and both issues can be covered by the MRESOLVER-9 title.
That said, I'm going to investigate this original fix and try to cherry-pick it at the same time.

**Comment by michael-o** [comment]
Thanks, looking forward to.

**Comment by gnodet** [comment]
I've opened #146 to use a different jira issue.

**Comment by jira-importer** [comment]
Resolve #808

**Comment by jira-importer** [comment]
Resolve #808

**Pull request closed without merging**
