### PR TITLE
[MRESOLVER-148] Use latest vanilla Guice4, no need for for forked one anymore.

### PR DESCRIPTION
**Pull request by cstamas**
https://issues.apache.org/jira/browse/MRESOLVER-148

Depends on https://github.com/apache/maven-resolver/pull/79

The commit from PR 79 will go away once that PR is merged.

### CODE REVIEW

**Comment by michael-o** [comment]
Going through...

**Comment by cstamas** [comment]
Updated to leave only meaningful changes (as dependant PR was merged), sorry if this force push messed you up, but wanted to prep it for clean merge.

**Comment by michael-o** [comment]
No issue, I did cherry-pick the relevant commit anyway.

**Comment by jira-importer** [comment]
Resolve #888

**Pull request closed without merging**
