### PR TITLE
[MRESOLVER-124] Remove deprecated API usages - httpclient

### PR DESCRIPTION
**Pull request by slachiewicz**
This change is [Reviewable](https://reviewable.io/reviews/apache/maven-resolver/59)

### CODE REVIEW

**Comment by michael-o** [comment]
Please read my comment from #48

**Comment by slachiewicz** [comment]
Ok I saw that. For next release we have plan to remove that module. Should I close my  this PR?

**Comment by michael-o** [comment]
I guess so, I see no need to maintain two codepaths if we can use Wagon throughout.

**Comment by jira-importer** [comment]
Resolve #857

**Comment by jira-importer** [comment]
Resolve #857

**Pull request closed without merging**
