### PR TITLE
[MRESOLVER-461] Cleanup in dep managers

### PR DESCRIPTION
**Pull request by cstamas**
3 of them were almost same.
* default: derives to infinity, always applies
* transitive: derives to infinity, applies after depth>=2
* classic: derives until depth>=2, applies after depth>=2

Note: "derives" means picks up depMgt from currently processed node. Hence, classic ignores all depMgt in graph coming from transitive dependencies. depth=1 is root (ie. project), depth=2 are first level deps (those listed in POM), etc.

---

https://issues.apache.org/jira/browse/MRESOLVER-461

### CODE REVIEW

**Review by gnodet — APPROVED** [review]

**Comment by michael-o** [comment]
There is no logical change, but only pulled up to a super class?

**Comment by cstamas** [comment]
Yes, a cleanup

**Comment by cstamas** [comment]
thing is: will do resolver - maven - IT run to test classic, but other two was never tested (so i can be only certain did not break them). Will also add UTs as only classic has rudimentary one

**Review by michael-o — APPROVED** [review]

**Comment by cstamas** [comment]
OK, the resolver master - maven master - maven IT master ran OK, so this shows that "classic" was undisturbed.

Next will do UTs and will merge this as I have your approvals.

**Comment by cstamas** [comment]
Removed `ClassicDependencyManagerTest` and added new `DependencyManagerTest` UT tests all 3 of implementations (all aspects, not only Optional as Classic UT did) with comments sprinkled explaining what they do.

**Comment by jira-importer** [comment]
Resolve #1140

**Pull request merged**
