### PR TITLE
[MRESOLVER-258] Collapse collectors

### PR DESCRIPTION
**Pull request by cstamas**
As DF (original) and BF (added in 1.8) started as copy-paste of each other, they
share a LOT. This PR tries to minimize redundancy, still, not loosing clarity,
so leaving inner Args class for each of them.

---

https://issues.apache.org/jira/browse/MRESOLVER-258

### CODE REVIEW

**Comment by michael-o** [comment]
@caiwei-ebay2 @caiwei-ebay can you have a look also?

**Review by michael-o — APPROVED** [review]
LGTM. Though, I would leave @caiwei-ebay2 a couple of days till Sat to bless as well.

**Comment by cstamas** [comment]
and @weibo1995

**Comment by michael-o** [comment]
@cstamas merge ahead!

**Comment by jira-importer** [comment]
Resolve #1383

**Comment by jira-importer** [comment]
Resolve #1383

**Comment by jira-importer** [comment]
Resolve #1383

**Pull request merged**
