### PR TITLE
[MRESOLVER-35] maven-resolver-impl move dependency collector and friends to subpackage

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Comment by michael-o** [comment]
Can you rebase a13091b8772435c0bb4967109e79d42d175b40b8 no top of master and drop commit for MRESOLVER-7? I want to merge your changes.

**Comment by slachiewicz** [comment]
Because this pull depends on #10 so You should first merge #10 to master then this pull request will look slightly better

**Comment by michael-o** [comment]
...makes it a bit hard to test isolated. I'll go on with your other PRs first and will wait until ASF JIRA is back online.

**Comment by michael-o** [comment]
@slachiewicz Can you please decouple this from MRESOLVER-7 competely?

**Comment by slachiewicz** [comment]
Done

**Comment by jira-importer** [comment]
Resolve #1362

**Pull request closed without merging**
