### PR TITLE
[MRESOLVER-176] Make TrackingFileManager use named locks as well

### PR DESCRIPTION
**Pull request by cstamas**
https://issues.apache.org/jira/browse/MRESOLVER-176

Use selected NamedLocksFactory in DefaultTrackingFileManager as well
to protected property file reads/writes.

### CODE REVIEW

**Comment by cstamas** [comment]
@cstamas note to myself: commit msg is wrong (contains wrong JIRA ref), but as this is draft, it will be rebased anyway and hence, message fixed as well.

**Comment by michael-o** [comment]
Won't fix, see JIRA issue.

**Comment by jira-importer** [comment]
Resolve #925

**Comment by jira-importer** [comment]
Resolve #900

**Pull request closed without merging**
