### PR TITLE
Example of using japicmp to ensure binary API compatibility

### PR DESCRIPTION
**Pull request by cstamas**
This now fails when building, as 1.8.x breaks vs 1.6.3
(and is ok, this is merely a "demo" that we should integrate)

### CODE REVIEW

**Review by michael-o — APPROVED** [review]

**Comment by cstamas** [comment]
https://github.com/siom79/japicmp/pull/326

**Comment by cstamas** [comment]
https://github.com/siom79/japicmp/pull/328

**Comment by cstamas** [comment]
Jenkins still uses Maven 3.8.5 and it fails due https://github.com/siom79/japicmp/issues/327

**Comment by cstamas** [comment]
This is on hold until https://github.com/siom79/japicmp/pull/328 gets merged and we got new release with that fix

**Comment by cstamas** [comment]
Updated to latest JApiCmp that has all the patches.

**Pull request merged**
