### PR TITLE
[MRESOLVER-107] update wagon api

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by michael-o** [comment]
I think the 3.0.0 is intentional. The API likely did not change since then.

**Comment by elharo** [comment]
so why release wagon-api 3.4.0 at all? Is there any reason to stick with the older version?

**Comment by michael-o** [comment]
It is released with the entire train. If you see now diff on the API, go ahead and update.

**Comment by jira-importer** [comment]
Resolve #887

**Comment by jira-importer** [comment]
Resolve #887

**Pull request merged**
