### PR TITLE
[MRESOLVER-184] Add destroy hook

### PR DESCRIPTION
**Pull request by cstamas**
And use this hook in Hz and Redisson implemenetations. Drop redundant
code from HZ as well.

### CODE REVIEW

**Comment by rfscholte** [comment]
Is this a candidate for autoclosable?

**Comment by cstamas** [comment]
> Is this a candidate for autoclosable?

@rfscholte um, could you elaborate your question a bit? NamedLockSupport IS AutoCloseable, so what you mean by "this"?

**Comment by rfscholte** [comment]
I was wondering if `destroy` was a synonym for `close`. Only for the latter you can use autoclosable. 
But is seems like that is already covered, so never mind.

**Comment by cstamas** [comment]
Superseded by https://github.com/apache/maven-resolver/pull/111

**Comment by jira-importer** [comment]
Resolve #1416

**Comment by jira-importer** [comment]
Resolve #1416

**Pull request closed without merging**
