### PR TITLE
[MRESOLVER-351] Thread count as core multiplied

### PR DESCRIPTION
**Pull request by slawekjaranowski**
Syntax as 1.5C for thread count parameters

Based on #237

### CODE REVIEW

**Review by michael-o — COMMENTED** [review]
Didn't we have this before and agreed that this has to happen on a higher level?

@cstamas

**Comment by slawekjaranowski** [comment]
On higher level all properties are pass as is, only resolver know which specific property means.

**Comment by michael-o** [comment]
This is not what I mean. I remember that we have agreed that higher level needs to do such calculations. I can't find the discussion. Maybe @cstamas can remember.

**Comment by cstamas** [comment]
https://github.com/apache/maven-resolver/pull/239#issuecomment-1420576532

**Comment by jira-importer** [comment]
Resolve #1026

**Comment by jira-importer** [comment]
Resolve #1026

**Pull request closed without merging**
