### PR TITLE
[MRESOLVER-136] switch to bnd-maven-plugin for generating bundle headers

### PR DESCRIPTION
**Pull request by kwin**
enable reproducible builds

### CODE REVIEW

**Comment by michael-o** [comment]
@hboutemy This one is for you!

**Comment by michael-o** [comment]
@hboutemy Can you evaluate this? I want to cut yet another release of Release soon.

**Review by michael-o — APPROVED** [review]
For testing purposes I have disabled SNAPSHOT resolution to timestamp:
```
mosipov@bsd1srv:/usr/home/mosipov/var/Projekte/maven-resolver-jars
$ diffoscope 19\:47\:38/ 19\:48\:44/
2020-10-02 19:49:33 W: diffoscope.main: Fuzzy-matching is currently disabled as the "tlsh" module is unavailable.
--- 19:47:38/
+++ 19:48:44/
├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ @@ -1 +1 @@
│ -drwxr-xr-x 2 mosipov mosipov 17 2020-10-02 17:47:46 131072 23 0x800
│ +drwxr-xr-x 2 mosipov mosipov 17 2020-10-02 17:49:12 131072 23 0x800
│   --- 19:47:38/demo.jar
├── +++ 19:48:44/demo.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 345 2020-10-02 17:47:15 4096 2 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 345 2020-10-02 17:47:48 4096 2 0x800
│   --- 19:47:38/maven-resolver-api-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-api-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 149118 2020-10-02 17:47:23 131072 517 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 149118 2020-10-02 17:48:55 131072 517 0x800
│   --- 19:47:38/maven-resolver-connector-basic-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-connector-basic-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 45754 2020-10-02 17:47:27 46080 91 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 45754 2020-10-02 17:49:00 46080 91 0x800
│   --- 19:47:38/maven-resolver-demo-maven-plugin-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-demo-maven-plugin-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 11908 2020-10-02 17:47:30 12288 25 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 11908 2020-10-02 17:49:02 12288 25 0x800
│   --- 19:47:38/maven-resolver-demo-snippets-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-demo-snippets-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 43005 2020-10-02 17:47:29 43008 85 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 43005 2020-10-02 17:49:02 43008 85 0x800
│   --- 19:47:38/maven-resolver-impl-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-impl-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 179618 2020-10-02 17:47:27 131072 517 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 179618 2020-10-02 17:48:59 131072 517 0x800
│   --- 19:47:38/maven-resolver-spi-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-spi-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 38436 2020-10-02 17:47:23 38912 77 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 38436 2020-10-02 17:48:56 38912 77 0x800
│   --- 19:47:38/maven-resolver-synccontext-global-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-synccontext-global-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 16520 2020-10-02 17:47:30 16896 34 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 16520 2020-10-02 17:49:03 16896 34 0x800
│   --- 19:47:38/maven-resolver-synccontext-redisson-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-synccontext-redisson-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 22251 2020-10-02 17:47:31 22528 45 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 22251 2020-10-02 17:49:03 22528 45 0x800
│   --- 19:47:38/maven-resolver-test-util-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-test-util-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 55457 2020-10-02 17:47:24 55808 110 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 55457 2020-10-02 17:48:56 55808 110 0x800
│   --- 19:47:38/maven-resolver-transport-classpath-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-transport-classpath-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 14721 2020-10-02 17:47:27 14848 30 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 14721 2020-10-02 17:49:00 14848 30 0x800
│   --- 19:47:38/maven-resolver-transport-file-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-transport-file-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 15668 2020-10-02 17:47:28 15872 32 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 15668 2020-10-02 17:49:00 15872 32 0x800
│   --- 19:47:38/maven-resolver-transport-http-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-transport-http-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 43644 2020-10-02 17:47:28 44032 87 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 43644 2020-10-02 17:49:01 44032 87 0x800
│   --- 19:47:38/maven-resolver-transport-wagon-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-transport-wagon-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 32841 2020-10-02 17:47:29 33280 66 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 32841 2020-10-02 17:49:01 33280 66 0x800
│   --- 19:47:38/maven-resolver-util-1.6.1-SNAPSHOT.jar
├── +++ 19:48:44/maven-resolver-util-1.6.1-SNAPSHOT.jar
│ ├── stat -t '%Y-%m-%d %H:%M:%S' -f '%Sp %l %Su %Sg %z %Sm %k %b %#Xf' {}
│ │ @@ -1 +1 @@
│ │ --rw-r--r-- 1 mosipov mosipov 168513 2020-10-02 17:47:25 131072 517 0x800
│ │ +-rw-r--r-- 1 mosipov mosipov 168513 2020-10-02 17:48:57 131072 517 0x800
```

**Review by elharo — COMMENTED** [review]
This seems to have broken Jenkins

**Comment by michael-o** [comment]
Working on this w/o giving up bnd-maven-plugin.

**Comment by jira-importer** [comment]
Resolve #840

**Pull request closed without merging**
