### PR TITLE
Please merge MRESOLVER-10 and MRESOLVER-33 into master.

### PR DESCRIPTION
**Pull request by ChristianSchulte**
This pull request just adds two new classes to the Maven Resolver without changing anything else. Those two classes are related to MRESOLVER-10 and MRESOLVER-33. It would be cool if this could be merged to the master branch @Apache. The resolver should provide those implementations. If Maven does not choose to use them, so be it. The Maven Resolver already provides other useful implementations not used by Maven. No reason not to merge this.

### CODE REVIEW

**Comment by michael-o** [comment]
Both merged.

**Comment by jira-importer** [comment]
Resolve #818

**Comment by jira-importer** [comment]
Resolve #1418

**Comment by jira-importer** [comment]
Resolve #818

**Pull request closed without merging**
