### PR TITLE
[MRESOLVER-361] Unreliable TCP and retries

### PR DESCRIPTION
**Pull request by cstamas**
Make httpClient retry for PUT.

---

https://issues.apache.org/jira/browse/MRESOLVER-361

### CODE REVIEW

**Comment by Eh2406** [comment]
Should this retry handler respect `aether.connector.http.retryHandler.count`?

**Comment by cstamas** [comment]
> Should this retry handler respect `aether.connector.http.retryHandler.count`?

This pr changes ONLY the fact that now client follows rfc2616 and treats listed methods (put among them) as idempotent.

**Comment by cstamas** [comment]
Latest commit exposes all aspects of retryHandler to users via config (defaults to "standard" handler as before in this PR)

**Comment by Eh2406** [comment]
Under what circumstances would a user want the standard retry handler?

**Comment by cstamas** [comment]
No idea, but presence of these options allows to make resolver work "as before". Just an escape hatch, nothing more.

**Pull request merged**
