### PR TITLE
[MRESOLVER-103] Move off from HttpClient deprecated classes

### PR DESCRIPTION
**Pull request by cstamas**
Just refresh the codebase to latest 4.x classes of HttpClient.

### CODE REVIEW

**Comment by michael-o** [comment]
Please see https://github.com/apache/maven-resolver/pull/48 and https://issues.apache.org/jira/projects/MRESOLVER/issues/MRESOLVER-121. I won't put any offer into this transport if Wagon Transport also works outside of Maven for Resolver. E.g, Ant Resolver Tasks.

**Comment by slachiewicz** [comment]
Grr same situation like with abdoned artifact-transfer

**Comment by cstamas** [comment]
@slachiewicz sorry, I did not check _closed PRs_ 😄  Also, I checked now and I see you did the "credentials charset" and some other nice changes, so will "lift them". Thanks!
@michael-o am pretty much sure http transport is used in use cases like now on ML and see Laird Nelson's project https://github.com/microbean/microbean-maven-cdi/blob/master/pom.xml

**Comment by cstamas** [comment]
Wagon in Maven (if you don't count maven-compat) is used ONLY indirectly, via resolver transport API -> resolver-transport-wagon -> Wagon. So it has indirection API on top of it and is adjusted to Resolver Transport API, so using it just adds "more moving parts". Moreover, as said above, Wagon was written for Maven 2, and it's API shows it's age, is archaic, clumsy, and many methods in Wagon exists ONLY to be unused, for example those for site publishing (that we gave up on). Furthermore, Wagon introduces many overlaps with Resolver and Maven itself (same problem stands with Resolver!): Maven spends cycles to adapt Maven Repository to Resolver Repository that adapts it to Wagon Repository (and so on, just a silly example, but again, is true).

Frankly, did not follow Wagon for 5-6 years, now tried to build it (could not), but did some stats: resolver-transport-http is 2k LOC and just a 42 kB JAR (contrast that to wagon-api alone, that is 6k LOC and makes 50 kB and you still have no transport). Am not quite sure people will be happy to pull Wagon into their projects (with all of it "whistle and bells"). Am not sure I would maintain in my free time 9k LOC (6k provider-api and 3k LOC http-shared+http) instead of 2k LOC (ok, this is gross simplification, but shows my point)?

Finally, as Resolver uses it's own API for transport, unsure is it wise to have yet-another-project that is "adapted" to given API, so more projects, more source lines, more git repositories, more releases (to wait for each other), and so on endlessly. We should radically lessen all these, the direction we should take is opposite: less projects (so less 72h waits for release), less git repositories, overall less LOC to maintain.

Maybe move remaining wagon bits (http, ssh) under resolver instead?

**Comment by michael-o** [comment]
Moving Wagon bits into Resolver won't work for two reasons:

1. Other Maven components use Wagon too
2. I don't want to maintain the codebase twice.

We need to think how to solve this better. If you have idea how to skim Wagon, I am all years for version 4.0.0.

**Comment by michael-o** [comment]
> 
> 
> @michael-o @slachiewicz I think this PR is not adding any code making us work more with it (is actually removes 100 LOC). So, IMO let's just merge this one and continue "where to go next" discussion elsewhere. Ok?

Go ahead, I trust you. Won't review.

**Pull request closed without merging**
