### PR TITLE
[MRESOLVER-437][MRESOLVER-438] Do not force set Expect-Continue setting

### PR DESCRIPTION
**Pull request by cstamas**
But allow users to override default (that comes from transport being in use). Also, ignore this setting on Java versions below 20. Finally, align class names for jdk transport as they were inconsistent.

---

https://issues.apache.org/jira/browse/MRESOLVER-437
https://issues.apache.org/jira/browse/MRESOLVER-438

### CODE REVIEW

**Review by rmannibucau — APPROVED** [review]
LGTM with a small side note (not blocking)

side note: think default http version should be 1.1 (until we enhance our protocol to use it somehow) cause http 2 has several issues (a lot of servers and some which can impact clients). Boost is not that huge once keep alive is on for us so let's not abuse it in our defaults?

PS: thanks for the hyphen typo fix ;)

**Comment by jira-importer** [comment]
Resolve #1108

**Comment by jira-importer** [comment]
Resolve #1112

**Comment by jira-importer** [comment]
Resolve #1112

**Comment by jira-importer** [comment]
Resolve #1108

**Pull request merged**
