### PR TITLE
Automatically format and sort imports according to the new maven coding style

### PR DESCRIPTION
**Pull request by gnodet**
See https://github.com/apache/maven-parent/pull/82

### CODE REVIEW

**Comment by michael-o** [comment]
What has applied the automagic?

**Comment by cstamas** [comment]
@gnodet what IDE and what style you use?

**Comment by cstamas** [comment]
> @gnodet what IDE and what style you use?

nvm, I see this is a plugin...

**Comment by gnodet** [comment]
> > @gnodet what IDE and what style you use?
> 
> nvm, I see this is a plugin...

The point is that the code is reformatted and the imports automatically organized.  It saves a bit of time ...  The two plugins are quite fast, especially as they do not process the files if they haven't been changed.
The checkstyle / code formatter have been somewhat aligned to maven codestyle.
Ideally, the configuration files would be shared between all maven repos.  I already reused those from https://github.com/apache/maven-build-cache-extension.

**Comment by cstamas** [comment]
I like it, but could we somehow share this setup (at least the huge config)? The amount of added LOC is not trivial, and have it copy-pasted over all reposes seems like a nightmare.....

**Comment by gnodet** [comment]
> I like it, but could we somehow share this setup (at least the huge config)? The amount of added LOC is not trivial, and have it copy-pasted over all reposes seems like a nightmare.....

Agreed.  I suppose the best location would be https://github.com/apache/maven-shared-resources/tree/master/src/main/resources/config ?

**Comment by cstamas** [comment]
Parent POM already provides this

**Pull request closed without merging**
