### PR TITLE
[MRESOLVER-36] Change internal logging to sl4j

### PR DESCRIPTION
**Pull request by slachiewicz**
please review

### CODE REVIEW

**Comment by slachiewicz** [comment]
ok, new version finished. 
After more tests (like replace .jar)  with maven 3.5.0/3.5.3 i need to leave more classes and initializations. Works fine as a swap in place.

**Comment by slachiewicz** [comment]
hi, any plan to verify this PR?

**Comment by jira-importer** [comment]
Resolve #768

**Comment by jira-importer** [comment]
Resolve #768

**Pull request merged**
