### PR TITLE
Remove unused hemcest test lib

### PR DESCRIPTION
**Pull request by slachiewicz**
It looks like this library has not been used by maven-resolver anymore

### CODE REVIEW

**Comment by michael-o** [comment]
I see a bit more when I run {{mvn dependency:analyze}}. Worth collecting with a JIRA issue and update this PR.

**Comment by slachiewicz** [comment]
{code}
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-api ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-spi ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-test-util ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-util ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-impl ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-connector-basic ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.6:test
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-transport-classpath ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.6:test
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-transport-file ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.6:test
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-transport-http ---
[WARNING] Used undeclared dependencies found:
[WARNING]    org.eclipse.jetty:jetty-http:jar:9.2.23.v20171218:test
[WARNING]    javax.servlet:javax.servlet-api:jar:3.1.0:test
[WARNING] Unused declared dependencies found:
[WARNING]    org.slf4j:jcl-over-slf4j:jar:1.7.25:runtime
[WARNING]    org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.6:test
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[WARNING]    org.eclipse.jetty:jetty-servlet:jar:9.2.23.v20171218:test
[WARNING]    org.slf4j:slf4j-simple:jar:1.7.25:test
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-transport-wagon ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.6:test
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-demo-snippets ---
[WARNING] Used undeclared dependencies found:
[WARNING]    org.apache.maven:maven-model-builder:jar:3.5.0:compile
[WARNING]    org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.3:compile
[INFO] --- maven-dependency-plugin:2.10:analyze (default-cli) @ maven-resolver-demo-maven-plugin ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.apache.maven.resolver:maven-resolver-util:jar:1.1.1-SNAPSHOT:compile
{code}

**Comment by jira-importer** [comment]
Resolve #964

**Comment by jira-importer** [comment]
Resolve #964

**Pull request closed without merging**
