### PR TITLE
[MRESOLVER-114] synchronize all calls to resolve on a single static lock

### PR DESCRIPTION
**Pull request by rreich**
The lock has to be static as there are multiple instances of this class.

### CODE REVIEW

**Comment by michael-o** [comment]
This will basically kill all concurrent access to non-affected artifacts. This is not a solution, but a workaround.

**Comment by rreich** [comment]
I think it's all I can offer. It is not elegant I know, but I cannot see any practical downsides and I'd rather waste some milliseconds than having race conditions.

**Comment by michael-o** [comment]
I consider this approach as superseded.

**Comment by jira-importer** [comment]
Resolve #890

**Pull request closed without merging**
