### PR TITLE
[MRESOLVER-385] Maven connection max ttl to wagon 300

### PR DESCRIPTION
**Pull request by cstamas**
To have it aligned with deprecated Wagon.

---

https://issues.apache.org/jira/browse/MRESOLVER-385

### CODE REVIEW

**Comment by kwin** [comment]
@cstamas I also prepared #317 just now. This additionally clarifies the meaning of this TTL. Feel free to pick one.

**Comment by cstamas** [comment]
https://github.com/apache/maven-resolver/pull/317 superseded this one

**Comment by jira-importer** [comment]
Resolve #1063

**Comment by jira-importer** [comment]
Resolve #1063

**Pull request closed without merging**
