### PR TITLE
[MRESOLVER-324] Make bf option as default

### PR DESCRIPTION
**Pull request by caiwei-ebay**
Not sure if it is appropriate time to apply for making bf as default option. At least it is chance to open this PR and started the discussion flow.

There were already some comments in the [MRESOLVER-324](https://issues.apache.org/jira/browse/MRESOLVER-324) and [MRESOLVER-7](https://issues.apache.org/jira/browse/MRESOLVER-7). The performance improvements is significant. And more and more users are adopting this option, at least eBay and @jhaber's company are widely adopting this option and no bigs issues found so far.

Meanwhile microsoft vscode has enabled this option by default since [0.9.0](
https://github.com/microsoft/vscode-java-pack/blob/667993fda7c41f8516f2ee0c69a02863b7d5b846/release-notes/v0.9.0.md?plain=1#L40), one issue reported, however this issue only happens when relocation + version range case and was already fixed [here](https://github.com/apache/maven-resolver/commit/6efe87aa26ddc6854392eb95fa4e0550617d50b3) by @cstamas .

Also there are some discussions about parallel downloading in [stackoverflow](https://stackoverflow.com/questions/32299902/parallel-downloads-of-maven-artifacts).

@michael-o @cstamas Please share your concerns here.

### CODE REVIEW

**Comment by cstamas** [comment]
We need to branch off 1.9.x first, then master made into 2.0.0...

**Review by michael-o — CHANGES_REQUESTED** [review]
Doc change necessary

**Review by michael-o — APPROVED** [review]
This is fine for me for next major version

**Comment by jira-importer** [comment]
Resolve #1002

**Comment by jira-importer** [comment]
Resolve #1002

**Pull request merged**
