### PR TITLE
[MRESOLVER-156] Manage Google Guava dependency independent

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes [https://issues.apache.org/jira/browse/MRESOLVER-156](https://issues.apache.org/jira/browse/MRESOLVER-156)

The runtime dependencies for Guava are explained in the last section of the  [README](https://github.com/google/guava/tree/v30.1) "Important Warnings" #3

### CODE REVIEW

**Comment by michael-o** [comment]
Is this consistent with Maven Core?

**Comment by michael-o** [comment]
Going through now in tandem with Maven PR.

**Comment by jira-importer** [comment]
Resolve #913

**Comment by jira-importer** [comment]
Resolve #913

**Pull request closed without merging**
