### PR TITLE
[MRESOLVER-536] Continue when FS does not support 'setLastModifiedTime'

### PR DESCRIPTION
**Pull request by Jurrie**

### CODE REVIEW

**Review by cstamas — APPROVED** [review]

**Comment by cstamas** [comment]
This probably needs to be done in other transports as well.... Jetty, Java HttpClient, etc...

**Comment by cstamas** [comment]
No, I will handle this. Many thanks for this report!

**Comment by Jurrie** [comment]
> PR has formatting issues, locally you could `mvn spotless:apply` and commit changes, but again, thanks for sharing the important bit.

I force-pushed these changes. Should be green all the way now! 😉

**Comment by cstamas** [comment]
I think this one is superseded by https://github.com/apache/maven-resolver/pull/468

**Comment by cstamas** [comment]
@michael-o see MRESOLVER-536, user explained there what and why

**Comment by cstamas** [comment]
Sure, will backport it. The release of 1.9.19 is scheduled for "soon":
https://issues.apache.org/jira/issues/?jql=project%20%3D%20MRESOLVER%20AND%20fixVersion%20%3D%201.9.19

**Comment by michael-o** [comment]
> @michael-o see [MRESOLVER-536](https://issues.apache.org/jira/browse/MRESOLVER-536), user explained there what and why

I did already, but that also means that if a file is created no mtime is set at all and reading should fail too.

**Comment by cstamas** [comment]
I found something like this https://robindotnet.wordpress.com/2015/02/27/datetime-stamps-and-azure-file-shares/

**Comment by cstamas** [comment]
Hm, actually this PR seems good enough for 1.9.x as there is not much to backport: this spot is _single use_ of Files.setLastModifiedTime!

**Comment by cstamas** [comment]
My proposal https://github.com/apache/maven-resolver/pull/469
Basically, just "align" and kill this one single place in whole 1.9.x codebase that uses `Files` and use `File` method that does not throws.

**Comment by cstamas** [comment]
@Jurrie are you ok with #468 and #469 ?

**Comment by Jurrie** [comment]
> @Jurrie are you ok with #468 and #469 ?

I sure am! I'm just glad that this is being picked up as quick as it is. You're welcome to close this one @cstamas.

**Comment by michael-o** [comment]
> I found something like this https://robindotnet.wordpress.com/2015/02/27/datetime-stamps-and-azure-file-shares/

Read it. Not very helpful.

**Comment by cstamas** [comment]
Superseded with https://github.com/apache/maven-resolver/pull/468 and https://github.com/apache/maven-resolver/pull/469

**Pull request closed without merging**
