### PR TITLE
[MRESOLVER-191] Document how to analyze lock issues

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Comment by michael-o** [comment]
Generated page: https://maven.apache.org/resolver-archives/resolver-LATEST/maven-resolver-named-locks/analyzing-lock-issues.html

**Review by cstamas — APPROVED** [review]
Awesome, big 👍

**Comment by jira-importer** [comment]
Resolve #1442

**Comment by jira-importer** [comment]
Resolve #1442

**Pull request merged**
