### PR TITLE
Maven Resolver 1.2.0 JIRA issues.

### PR DESCRIPTION
**Pull request by ChristianSchulte**

### CODE REVIEW

**Comment by olamy** [comment]
@ChristianSchulte maybe we can close this one?

**Comment by michael-o** [comment]
I object. There are many good changes and fixes for out shortcomings. They must be considered for 2.0.

**Comment by olamy** [comment]
@michael-o no worries but the pr need to be rebased and there is so many commits/changes with the same pr....

**Comment by michael-o** [comment]
@ChristianSchulte Can you please factor out remaining bits which have not been merged yet?

**Comment by michael-o** [comment]
08295f824f1ab47c752c5a1a1dcda1c3e75cfc96 Is now a branch.

**Comment by michael-o** [comment]
422698e3b0eeb26d86ba6a167f8d257b4d89875a is now a branch.

**Comment by michael-o** [comment]
913aa9016fa8651bf801ce703d673d8c78caa480 is now a branch.

**Comment by michael-o** [comment]
All of these changes are now either merged, have branches or have PRs. Closing this umbrella PR.

**Comment by jira-importer** [comment]
Resolve #791

**Comment by jira-importer** [comment]
Resolve #791

**Pull request closed without merging**
