### PR TITLE
[MRESOLVER-272] Update parent POM to 37, remove plugin version overrides, update bnd

### PR DESCRIPTION
**Pull request by cstamas**
Remove version overrides and update bnd plugin
as well.

---

https://issues.apache.org/jira/browse/MRESOLVER-272

### CODE REVIEW

**Comment by cstamas** [comment]
@michael-o take a look at this one as well ,please.... seems some ignores changed, similar to those you discuss on ML?

**Comment by michael-o** [comment]
Yes, @kwin knows how to deal with.

**Comment by kwin** [comment]
@cstamas Can you enable https://creadur.apache.org/rat/apache-rat-plugin/check-mojo.html#consoleOutput in the root pom.xml's plugin configuration so that it is more easy to see where the failure is? I assume it is related to https://issues.apache.org/jira/browse/RAT-308. We can either add the Apache License header to it or add it to the ignores.

**Comment by slawekjaranowski** [comment]
I added `.gitattributes` to excluded list for RAT in https://github.com/apache/maven/pull/792

**Review by slawekjaranowski — APPROVED** [review]

**Comment by kwin** [comment]
Not sure about IP of a gitignore file but to me it seems safer to add an Apache License header to it according to https://www.apache.org/legal/src-headers.html#faq-exceptions.

**Comment by cstamas** [comment]
IMHO, git config files carries no IP...  they are more "environment" or so...

**Comment by slawekjaranowski** [comment]
I don't see **creativity** in .git* files - so IMHO header is not needed

**Review by kwin — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #761

**Pull request merged**
